CXX := g++
CXXFLAGS := -Wall -Wextra -O2 -std=c++17 -MMD -MP -Iinc

SRC_DIR := src
INC_DIR := inc
BUILD_DIR := build
BIN_DIR := bin
TARGET := $(BIN_DIR)/app

# Find all .cpp files in SRC_DIR
SRCS := $(wildcard $(SRC_DIR)/*.cpp)
# Convert source paths to object paths in BUILD_DIR
OBJS := $(SRCS:$(SRC_DIR)/%.cpp=$(BUILD_DIR)/%.o)
# Dependency files generated by -MMD
DEPS := $(OBJS:.o=.d)

# Default target
all: $(TARGET)

# Link object files into final executable
$(TARGET): $(OBJS)
	@mkdir -p $(BIN_DIR)
	$(CXX) $(CXXFLAGS) $^ -o $@

# Compile .cpp to .o
$(BUILD_DIR)/%.o: $(SRC_DIR)/%.cpp
	@mkdir -p $(BUILD_DIR)
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Include dependency files if they exist
-include $(DEPS)

# Clean build artifacts
clean:
	rm -rf $(BUILD_DIR) 
	rm -f $(TARGET)

# Run the program
run: $(TARGET)
	./$(TARGET)

.PHONY: all clean run
